### ISSUE TITLE
Error if we see an unrecognized YAML key is used in EE.yml

### ISSUE THREAD

**Issue by rooftopcellist** [ansible/ansible-builder#136]
When we parse the execution-environments.yml file, we should error early if an unrecognized key is provided.  Currently it is just silently not found and returns `None`.  

For example, this is an invalid execution-environment.yml

```
[chadams@chadams-work ansible-builder-play]$ cat execution-environment.yml 
---
version: 1
base_image: 'quay.io/ansible/ansible-runner:stable-2.10.devel'
requirements:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
```

(`requirements:` should actually be `dependencies:`)
