### ISSUE TITLE
Prepend steps don't work since moving to multi-stage builds

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible-builder#144]
Example:

```yaml
---
version: 1
dependencies:
  galaxy: requirements/collections_requirements.yml
  system: requirements/bindep_requirements.txt
additional_build_steps:
  prepend:
    - RUN pip3 install --upgrade pip setuptools
    - RUN dnf config-manager --set-enabled epel
```

yields Containerfile

```
FROM quay.io/ansible/ansible-runner:devel as builder

RUN pip3 install --upgrade pip setuptools
RUN dnf config-manager --set-enabled epel
ADD requirements.yml /build/

RUN ansible-galaxy role install -r /build/requirements.yml --roles-path /usr/share/ansible/roles
RUN ansible-galaxy collection install -r /build/requirements.yml --collections-path /usr/share/ansible/collections

RUN mkdir -p /usr/share/ansible/roles /usr/share/ansible/collections

FROM quay.io/ansible/ansible-runner:devel

COPY --from=builder /usr/share/ansible/roles /usr/share/ansible/roles
COPY --from=builder /usr/share/ansible/collections /usr/share/ansible/collections

ADD bindep_output.txt /build/
RUN dnf -y install $(cat /build/bindep_output.txt)
ADD requirements_combined.txt /build/
RUN pip3 install --upgrade -r /build/requirements_combined.txt
```

But that's not right, because `RUN dnf config-manager --set-enabled epel` happens inside of the `builder` image and later `RUN dnf -y install $(cat /build/bindep_output.txt)` happens inside of the 2nd (and final) image.

The prepend steps should probably act on the 2nd image, not the first ephemeral image
