### ISSUE TITLE
Errors spinning up EE pod

### ISSUE THREAD

**Issue by weiyentan** [ansible/ansible-builder#208]
I did my first attempt to create an execution environment. I am able to download ansible-builder1.0.0.0a1.

I build an execution-environment .yml with the referenced requirements.yml requirements.txt and i have a appened task of installing in some binaries. (copies below).  It compiles but I get errors like this.

```
Traceback (most recent call last): File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1397, in run res = receptor_job.run() File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2957, in run return self._run_internal(receptor_ctl) File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 3008, in _run_internal raise RuntimeError(detail) RuntimeError: Error creating pod: container failed with exit code 126:
```
I have attempted to move the install of the powershell stuff into the append block  but I still get errors, and even removed, and still got the same errors. 

I am quite excited to get this up and running. but i am struggling to understand how I can get things going. Any help most appreciated. 
```
execution_environment.yml
---
version: 1
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend: |
     RUN curl https://packages.microsoft.com/config/rhel/7/prod.repo | tee /etc/yum.repos.d/microsoft.repo
     RUN yum install -y powershell
  append:
    - RUN alternatives --set python /usr/bin/python3
    - COPY --from=quay.io/project-receptor/receptor:0.9.7 /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - ADD run.sh /run.sh
    - CMD /run.sh
    - USER 1000
    - RUN git lfs install
```
my requirements.txt
```
pypsrp
awxkit>=19.0.0
urllib3
git+https://github.com/ansible/ansible-builder.git@devel#egg=ansible-builder

```
and my requirements.yml
```
---
collections:
  - awx.awx
  - redhat_cop.tower_configuration
  - community.general

```

I have the package in dockerhub  under https://hub.docker.com/layers/weiyentan2/prometheus_ansible-ee/0.8/images/sha256-97524aefda9a8dda2b95cfb892b104434c0a4ee3b3efe0fa38d1d2a41a3ea943?context=repo

The docker list is listed as:

```
ADD file ... in /
71.7 MB
2
LABEL org.label-schema.schema-version=1.0 org.label-schema.name=CentOS Base
0 B
3
CMD ["/bin/bash"]
0 B
4
ARG CONTAINER_IMAGE=quay.io/centos/centos:8
0 B
5
ARG CONTAINER_IMAGE=quay.io/centos/centos:8 REMOTE_SOURCE_DIR=/remote-source
0 B
6
COPY dir:2606a65627042f34a8cd2f85adfa9356e8b10f2926fb6ef534b2234f84ef658c in $REMOTE_SOURCE_DIR
55.94 KB
7
WORKDIR $REMOTE_SOURCE_DIR/app
0 B
8
|2 CONTAINER_IMAGE=quay.io/centos/centos:8 REMOTE_SOURCE_DIR=/remote-source /bin/sh -c
31.57 MB
9
|2 CONTAINER_IMAGE=quay.io/centos/centos:8 REMOTE_SOURCE_DIR=/remote-source /bin/sh -c
21.49 MB
10 CONTAINER_IMAGE=quay.io/centos/centos:8 REMOTE_SOURCE_DIR=/remote-source /bin/sh -c
297 B
11 CONTAINER_IMAGE=quay.io/centos/centos:8 REMOTE_SOURCE_DIR=/remote-source /bin/sh -c 2.51 MB
12  CONTAINER_IMAGE=quay.io/centos/centos:8 REMOTE_SOURCE_DIR=/remote-source /bin/sh -c
6 MB
13 WORKDIR /0 B
14 CONTAINER_IMAGE=quay.io/centos/centos:8 REMOTE_SOURCE_DIR=/remote-source /bin/sh -c
96 B
15 ENTRYPOINT ["/usr/local/bin/dumb-init", "--"]
0 B
16 COPY dir:41761b9152fbcc34467f989adff961d4728a03d11f716fed93034f20087a0752 in /output
8.22 MB
17 /bin/sh -c /output/install-from-bindep
54.47 MB
18 /bin/sh -c for dir in
911 B
19 VOLUME /runner 0 B
20 WORKDIR /runner 0 B
21 ENV HOME=/home/runner 0 B
22 ADD file ... in /bin/entrypoint 990 B
23 /bin/sh -c chmod +x /bin/entrypoint
42 B
24 ENTRYPOINT ["entrypoint"]
0 B
25 CMD ["ansible-runner", "run", "/runner"]
0 B
26 COPY dir:18fe3b13d828f4d18ff3aa7c694f94fbd9b4c32a52dcfa453a99ec29cc112383 in /usr/share/ansible
6.05 MB
27 COPY dir:70ff169f5bda0973f396098cd90f442150060b2c5d357729c144f38e33df593a in /output/
46.27 MB
28 /bin/sh -c /output/install-from-bindep && rm
79.87 MB
29 /bin/sh -c curl https://packages.microsoft.com/config/rhel/7/prod.repo |
260 B
30 /bin/sh -c yum install -y 114.65 MB
31 /bin/sh -c alternatives --set python
435 B
32 COPY file:572c957ca432e5f6b2268a81ceb9e3285f09d10f8540d7b0c48c71c9485d429a in /usr/bin/receptor
18.52 MB
33 /bin/sh -c mkdir -p /var/run/receptor 116 B
34 ADD file ... in /run.sh 153 B
35 CMD ["/bin/sh" "-c" "/run.sh"]0 B
36USER 1000 0 B
37/ bin/sh -c git lfs install
```
