### ISSUE TITLE
Process direct requirements and additional build steps from the user's spec

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible-builder#21]
Example `execution-environment.yml`:

(EDIT: direct listing of system dependencies not supported after all)

```yaml
---
version: 1
dependencies:
  python: requirements.txt
  system:
    - git

additional_build_steps: |
  RUN some-command
  ENV SOME_VAR=some_value
```

This tool should output a Container file with:

 - `pip` install for requirements
 - `dnf`? install for system requirement
 - additional lines for whatever is given in the additional specs

Schema of EE spec is subject to change, but for now we want to just get something in.

Note that `galaxy` in dependencies is processed in the current code base.

**Comment by kdelee** [comment]
@AlanCoding example given in issue has a couple problems:

1) https://github.com/ansible/ansible-builder/issues/50 is not done, including the list of system dependencies causes a traceback, but will delay looking at that until the issue is closed
2) looks like code can't handle the multiline string you are using in your example, it wants a `prepend` and/or `append` section

```
cat execution-environment.yml 
---
version: 1
dependencies:
  python: requirements.txt

additional_build_steps: |
  RUN touch foo
  ENV ELIJAH_VAR=elijah
```

```
 ansible-builder build
requirements.txt
requirements.txt
Traceback (most recent call last):
  File "/home/elijah/.cache/pypoetry/virtualenvs/ansible-builder-d47oRQeY-py3.8/bin/ansible-builder", line 11, in <module>
    load_entry_point('ansible-builder', 'console_scripts', 'ansible-builder')()
  File "/home/elijah/sfw/ansible/ansible-builder/ansible_builder/cli.py", line 20, in run
    if action():
  File "/home/elijah/sfw/ansible/ansible-builder/ansible_builder/main.py", line 57, in build
    self.containerfile.prepare_prepended_steps()
  File "/home/elijah/sfw/ansible/ansible-builder/ansible_builder/main.py", line 205, in prepare_prepended_steps
    prepended_steps = additional_prepend_steps.get('prepend')
AttributeError: 'str' object has no attribute 'get'
```

looks like need to gracefully reject a `additional_build_steps` section that is not a dictionary 

put up a PR with possible error message enhancement

**Comment by kdelee** [comment]
now testing w/ proper syntax, and its working for me:
```
---
version: 1
dependencies:
  python: requirements.txt

additional_build_steps:
  prepend: |
    ENV ELIJAH_VAR=elijah
```
building the image and then inspecting the environment shows my environment variable was set.

This is another case for our basic integration tests for when we get those added to the repo

**Comment by AlanCoding** [comment]
Sorry about the example, it has been a moving target. The syntax has evolved over time. You can still do:

```yaml
---
version: 1
dependencies:
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend: |
    ENV ELIJAH_VAR=elijah
```

And the last piece of #50 is integrating `bindep.txt` from collections into the mix, which is the current item I'm trying to get cleared up and finished. If you do it this way, the `bindep.txt` file next to your `execution-environment.yml` file can list git as an rpm type dependency.
