### ISSUE TITLE
Validation needed for dependencies in execution-environment.yml

### ISSUE THREAD

**Issue by TimGrt** [ansible/ansible-builder#241]
Using ansible-builder for creating an EE, I came across this error:
```bash
$ ansible-builder build
AttributeError: 'str' object has no attribute 'get'
```
This error is fairly meaningless, I malformed the dependencies section (didn't use key-value pairs):
```yaml
---
version: 1

build_arg_defaults:
  ANSIBLE_RUNNER_IMAGE: 'quay.io/ansible/ansible-runner:stable-2.10-devel'
  
dependencies:
  requirements.yml
  requirements.txt
```
Providing a useful error message would help, stating the required type and available options, e.g.
```bash
$ ansible-builder build
ansible_builder.exceptions.DefinitionError: 
Error: Unknown type <class 'str'> found for dependencies, must be a dict.

Allowed options are:
['galaxy', 'python', 'system']
```

Additionally, no validation is done for provided key-value pairs in dependencies section, this execution-environment.yml will be build:
```yaml
---
version: 1

build_arg_defaults:
  ANSIBLE_RUNNER_IMAGE: 'quay.io/ansible/ansible-runner:stable-2.10-devel'
  
dependencies:
  test: requirements.yml
  anothertest: requirements.txt
  somestuff: stuff.txt
```
It should be checked for invalid keys, even though a (more or less) usable Container image is created but naturally without any dependencies installed.
