### ISSUE TITLE
Install collections to multiple locations

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansible-builder#246]
The user should have the option to give multiple galaxy requirements file to install to different folders inside of the image.

Spitballing syntax:

```yaml
---
version: 1
dependencies:
  galaxy:
    /usr/share/ansible/collections: requirements.yml
    /usr/share/automation-controller/collections: more_requirements.yml
```

Second location is taken from https://github.com/ansible/awx/pull/10323

Given this syntax, ansible-builder will install both requirements file to their respective locations. Then, the Containerfile will include COPY lines for _both_ locations, and `ansible-builder introspect` may take multiple arguments for multiple locations.

I'm anticipating this will be a part of @pabelanger's requirements eventually, but I want to be sure I have it right.
