### ISSUE TITLE
Can't open file '/ansible_builder_mount/introspect.py

### ISSUE THREAD

**Issue by AdamMack2007** [ansible/ansible-builder#251]
I am receiving the following error when running the build process:

## Error

```
amack@MacBook-Pro` ansible-builder % ansible-builder build --tag network_ee --container-runtime docker -f execution-environment.yml --context ./context
Running command:
  docker build -f ./context/Dockerfile -t network_ee ./context
Running command:
  docker run --rm -v /usr/local/lib/python3.9/site-packages/ansible_builder:/ansible_builder_mount:Z network_ee python3 /ansible_builder_mount/introspect.py
python3: can't open file '/ansible_builder_mount/introspect.py': [Errno 2] No such file or directory

An error occured (rc=2), see output line(s) above for details.
```

## Versions
Ansible-builder == 0.4.0
Ansible == 2.9.21

## EE definition file:
```
---
version: 1
dependencies:
  galaxy: requirements.yml
  python: requirements.txt

build_arg_defaults:
  ANSIBLE_RUNNER_IMAGE: "ansible/ansible-runner:latest"

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools
  append:
    - RUN ls -la /etc

```
## Directory Structure:

```
├── context
│   ├── Dockerfile
│   └── _build
│       └── requirements.yml
├── execution-environment.yml
├── introspect.py
├── requirements.txt
└── requirements.yml

```
