### ISSUE TITLE
Can't build new image because of 'non root' user

### ISSUE THREAD

**Issue by Seb0042** [ansible/ansible-builder#258]
Hello,

Here is my execution-environment.yml:
```
---
version: 1
build_arg_defaults:
    ANSIBLE_RUNNER_IMAGE: 'quay.io/ansible/awx-ee:0.3.0'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools

  append:
    - ADD pmp.py /usr/local/lib/python3.8/site-packages/ansible/plugins/lookup/
``` 
Each time I'm lauching a build it fails with this error:
```
Step 16/17 : RUN /output/install-from-bindep && rm -rf /output/wheels
 ---> Running in 8cc5c9c6290c
+ PKGMGR=
+ PKGMGR_OPTS=
+ '[' -z ']'
+ PKGMGR=/usr/bin/dnf
+ '[' -f /usr/bin/microdnf ']'
+ /usr/bin/dnf update -y
Error: This command has to be run with superuser privileges (under the root user on most systems).
The command '/bin/sh -c /output/install-from-bindep && rm -rf /output/wheels' returned a non-zero code: 1
``` 
So every time I have to modify the Dockerfile in context directory and add "User root" in it and then launch the build with a docker command.
