### ISSUE TITLE
Document and test the "compile" bindep profile

### ISSUE THREAD

**Issue by shanemcd** [ansible/ansible-builder#340]
In the stage where we pre-build the wheels, the `assemble` script looks for a profile labeled [`compile`](https://github.com/ansible/python-builder-image/blob/main/scripts/assemble#L65), which allows us to install build-time only dependencies that do not end up in the final image.

An example:

```yaml
# execution-environment.yml
---
version: 1
dependencies:
  system: bindep.txt
  python: requirements.txt
```

```
# requirements.txt
durable_rules
```

```
# bindep.txt
gcc [compile]
python38-devel [compile]
```
