### ISSUE TITLE
Ansible builder command fails with "Failed to download metadata for repo 'appstream'"

### ISSUE THREAD

**Issue by tombosmansibm** [ansible/ansible-builder#343]
I've tried several base images, the last one I tried was this:

quay.io/ansible/ansible-runner:stable-2.12-devel

`Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist`

I've added this to the ContainerFile directly (prepend does not work)

```
RUN dnf --disablerepo '*' --enablerepo=extras swap centos-linux-repos centos-stream-repos
RUN dnf -y distro-sync
RUN dnf -y update
```

and I removed the assemble step
`RUN assemble`

I can build the image then, using the podman build command directly, but I guess I'm missing some things in my execution environment now.

**Comment by tombosmansibm** [comment]
Nevermind, I pulled a newer version of the builder image , and now it's working fine.

**Comment by rafabono** [comment]
Hi, I have the same problem building my image. My execution-environment.yml looks like this:

```yaml
---
version: 1
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt


additional_build_steps:
  append:
    - RUN alternatives --set python /usr/bin/python3
    - COPY --from=quay.io/project-receptor/receptor:0.9.7 /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - ADD run.sh /run.sh
    - CMD /run.sh
    - USER 1000 
    - RUN git lfs install
```
What changes have you made to make it work for you?

Thanks.
