### ISSUE TITLE
Introspect and Build conflict in handling execution-enviornment.yml requirements path 

### ISSUE THREAD

**Issue by alisonlhart** [ansible/ansible-builder#393]
Standard format for collections is that the requirements.txt file is kept in the root of the collection and the execution-environment.yml file is in the meta/ directory. If you build within the collection root, `ansible-builder build` will fail if relative pathing for the requirements.txt and bindep.txt files are not used:

`meta/execution-environment.yml` file
```
---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:stable-2.10-devel'

dependencies:
  python: requirements.txt
```
`ansible-builder build` failure in collection root:
```
$ ansible-builder build -c . -f meta/execution-environment.yml
**Dependency file requirements.txt does not exist.**
```
However, `ansible-builder introspect` will work with this setup. 
```
$ ansible-builder introspect collections/
# Dependency data for collections/
---
python:
  netapp.ontap:
  - ipaddress
  - jmespath
  - netapp-lib
  - requests
  - six
  - solidfire-sdk-python
  - xmltodict
```

If you switch to relative pathing for the requirements.txt file in the execution-environment.yml file, `introspect` fails and `build` succeeds.

`meta/execution-environment.yml`
```
---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:stable-2.10-devel'

dependencies:
  python: ../requirements.txt
```
`build` succeeds in collection root :
```
$ ansible-builder build -c . -f meta/execution-environment.yml
Running command:
  podman build -f ./Containerfile -t ansible-execution-env:latest .
Complete! The build context can be found at: /home/ali/collections/ansible_collections/netapp/ontap
```

`introspect` fails :
```
$ ansible-builder introspect collections/
Expected requirements file not present at: /home/ali/collections/ansible_collections/netapp/requirements.txt
FileNotFoundError: [Errno 2] No such file or directory: 'collections/ansible_collections/netapp/ontap/../requirements.txt'
```
It appears `ansible-builder introspect` is not able to interpret the relative path in the execution-environment.yml file even though `ansible-builder build` requires it.
