### ISSUE TITLE
ansible-builder introspect is failing

### ISSUE THREAD

**Issue by Jennifer-John** [ansible/ansible-builder#406]
Hi team,
Adding to the issue https://github.com/ansible/ansible-builder/issues/399
I am trying to build the execution environment for the dellemc ansible modules.
I have the execution-environment.yml file in the meta folder and the requirements.yml and requirements.txt in the root directory. So i have specified the relative path of the requirements.yml and requirements.txt in the execution-environment.yml as below
```
---
version: 1
dependencies:
  galaxy: ../requirements.yml
  python: ../requirements.txt
```
I am trying to create the environment using ansible-builder build --tag test  --container-runtime docker and it fails with the below error FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/ansible/collections/ansible_collections/dellemc/powerscale/../requirements.txt' .Editing as below does not work when i run _ansible-builder build --tag my-env --container-runtime docker_ with file requirements.yml does not exist

```
---
version: 1
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
```
As per guidelines, the execution-environment should be in the meta folder, hence we have specified the relative path of the requirements.txt and requirements.yml files as mentioned here https://docs.ansible.com/automation-controller/latest/html/userguide/ee_reference.html#ansible-galaxy-dependencies
