### ISSUE TITLE
Building error: "ansible-galaxy: not found"

### ISSUE THREAD

**Issue by avalou** [ansible/ansible-builder#409]
### Description of the issue
During the building process, ansible-builder stops with the following error message:
```
Step 9/24 : RUN ansible-galaxy role install -r requirements.yml --roles-path "/usr/share/ansible/roles"
 ---> Running in bb4f91c3db34
/bin/sh: 1: ansible-galaxy: not found
The command '/bin/sh -c ansible-galaxy role install -r requirements.yml --roles-path "/usr/share/ansible/roles"' returned a non-zero code: 127
``` 

### Steps to reproduce
**execution-environment.yml**
```
---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'ubuntu:22.04'

ansible_config: 'ansible.cfg'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  append:
    - COPY ./filters/* /usr/share/ansible/plugins/filter
    - COPY ./libraries/* /us:r/share/ansible/plugins/modules
```

**requirements.txt**
```
ansible-core==2.12.7
docker-compose
```

**requirements.yml**
```
---
collections:
  - name: community.general
  - name: openstack.cloud
```

**bindep.txt**
```
python3 [platform:dpkg]
python3-pip [platform:dpkg]
dnsutils [platform:dpkg]
openssl [platform:dpkg]
docker [platform:dpkg]
docker-compose [platform:dpkg]
```

1. `ansible-builder build --container-runtime=docker`

### My system
I run ansible-builder version 1.1.0 on ubuntu server 22.04, with ansible [core 2.12.7].
