### ISSUE TITLE
variable ansible_config not working

### ISSUE THREAD

**Issue by Mrmel94** [ansible/ansible-builder#413]
Hi, I'm using ansible-builder 1.1.0 with this file : 

```
---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:latest'

ansible_config: 'ansible.cfg'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend: |
    RUN whoami
    RUN cat /etc/os-release
  append:
    - RUN echo This is a post-install command!
    - RUN ls -la /etc
    - RUN ansible --version
```

The file ansible.cfg is at the same level of directory, and when I start the build I can see in the logs that my ansible.cfg is found and copied : 

`Step 6/26 : ADD _build/ansible.cfg ~/.ansible.cfg`

But once the build over and when I'm trying to use my custom EE, My awx can't see the file.

For the moment my workaround is to run this in additional_build_steps to use /etc/ansible/ansible.cfg instead : 

```
additional_build_steps:
  append:
    - RUN mkdir /etc/ansible
    - RUN touch /etc/ansible/ansible.cfg
    - RUN echo -e "[defaults]\nforks = 100\n\n[ssh_connection]\nretries = 3" > /etc/ansible/ansible.cfg
    - RUN cat /etc/ansible/ansible.cfg
    - RUN ansible --version
```

But it's not a very good solution.. and I don't understand why my variable doesn't works.

Thanks

**Comment by williamhanseneric** [comment]
Confirmed, the steps say

USER root
ADD _build/ansible.cfg ~/.ansible.cfg

But /root/ansible.cfg does not exist in the container after building it out and running it.

**Comment by Shrews** [comment]
Hi,

Admittedly, the documentation around this is not very clear, and something we should fix. But the use of the `ansible_config` setting is for adding a custom ansible configuration for the Galaxy build phase (where collections/roles are installed from a Hub server). The intention is not for the configuration file to end up in the final phase (and thus the final image).

The new version of builder, that is currently in development with no ETA as of yet, will allow for adding arbitrary files to the final image, and will allow for much more customization of the various build steps.

Since this is the intended behavior, we don't consider this a bug. However, I'm going to leave this open as a documentation bug so we can add some clarifying text to this option.

**Comment by Akasurde** [comment]
With Ansible Builder v3, you can achieve this like - 

```yaml
---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:latest

dependencies:
    ansible_core:
        package_pip: ansible-core==2.15.0
    ansible_runner:
        package_pip: ansible-runner==2.3.2
    galaxy:
        collections:
            - ansible.utils

additional_build_files:
    - src: files/ansible.cfg
      dest: configs

additional_build_steps:
    prepend_final:
        - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg

options:
    package_manager_path: /usr/bin/microdnf
```

```
# podman run -it ansible_cfg cat /etc/ansible/ansible.cfg
[defaults]
forks = 100

[ssh_connection]
retries = 3
```
