### ISSUE TITLE
Issue building an Execution Environment

### ISSUE THREAD

**Issue by kammerdiener** [ansible/ansible-builder#419]
Currently, we are using `ansible-builder` to add in some python dependencies as well as some galaxy dependencies that are necessary. We resolved some of our python dependency issues, but we are now running into this error: 
```
Traceback (most recent call last):
  File "/usr/local/bin/ansible-runner", line 5, in <module>
    from ansible_runner.__main__ import main
  File "/usr/local/lib/python3.8/site-packages/ansible_runner/__main__.py", line 48, in <module>
```

We are using the latest for the base and builder images: 
```
ARG EE_BASE_IMAGE=quay.io/ansible/ansible-runner:latest
ARG EE_BUILDER_IMAGE=quay.io/ansible/ansible-builder:latest
```

We are trying to add the following Python Dependencies: 
```
hvac==0.11.2
pyvmomi==7.0.3
dnspython==2.2.1
```

As well as the following Ansible Galaxy Dependencies
```
collections:
  - name: community.vmware
  - name: community.hashi_vault
  - name: ansible.posix
  - name: cyberark.pas
```

Any guidance would be greatly appreciated!
