### ISSUE TITLE
ERROR: No matching distribution found

### ISSUE THREAD

**Issue by joelwking** [ansible/ansible-builder#433]
I'm running: `ansible-builder --version 1.2.0` and `Python 3.9.14`  and `Red Hat Enterprise Linux release 9.1 (Plow)`.

The `RUN assemble` command is failing on the Python packages. If I `pip install` the packages in the requirements file, they install correctly.  If I remove the reference to `ciscoisesdk` from the requirements file, it will simply fail on another package with a similar error.

```text
(builder) [joelwking@aap janssen]$ ansible-builder build  --tag joel/janssen  -f execution-environment.yml
Running command:
  podman build -f context/Containerfile -t joel/janssen context
...showing last 20 lines of output...
  Downloading protobuf-4.21.10-cp37-abi3-manylinux2014_x86_64.whl (408 kB)
Collecting jsonschema==3.2.0
  Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting textfsm
  Downloading textfsm-1.1.3-py2.py3-none-any.whl (44 kB)
Collecting ttp
  Downloading ttp-0.9.1-py2.py3-none-any.whl (84 kB)
Collecting pyang
  Downloading pyang-2.5.3-py2.py3-none-any.whl (592 kB)
Collecting ansible==6.6.0
  Downloading ansible-6.6.0-py3-none-any.whl (42.3 MB)
Collecting dnacentersdk>=2.5.5
  Downloading dnacentersdk-2.5.5-py3-none-any.whl (2.8 MB)
Collecting ipaddress
  Downloading ipaddress-1.0.23-py2.py3-none-any.whl (18 kB)
Collecting ciscoisesdk==2.0.8,>=2.0.8
  Downloading ciscoisesdk-2.0.8-py3-none-any.whl (2.9 MB)
ERROR: Could not find a version that satisfies the requirement requests==2.22.0,==2.28.1,>=2.25.1,>=2.4.2 (from -r /tmp/src/requirements.txt (line 23)) (from versions: 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.6, 0.10.7, 0.10.8, 0.11.1, 0.11.2, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 0.13.9, 0.14.0, 0.14.1, 0.14.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 2.0.0, 2.0.1, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.7.0, 2.8.0, 2.8.1, 2.9.0, 2.9.1, 2.9.2, 2.10.0, 2.11.0, 2.11.1, 2.12.0, 2.12.1, 2.12.2, 2.12.3, 2.12.4, 2.12.5, 2.13.0, 2.14.0, 2.14.1, 2.14.2, 2.15.1, 2.16.0, 2.16.1, 2.16.2, 2.16.3, 2.16.4, 2.16.5, 2.17.0, 2.17.1, 2.17.2, 2.17.3, 2.18.0, 2.18.1, 2.18.2, 2.18.3, 2.18.4, 2.19.0, 2.19.1, 2.20.0, 2.20.1, 2.21.0, 2.22.0, 2.23.0, 2.24.0, 2.25.0, 2.25.1, 2.26.0, 2.27.0, 2.27.1, 2.28.0, 2.28.1)
ERROR: No matching distribution found for requests==2.22.0,==2.28.1,>=2.25.1,>=2.4.2 (from -r /tmp/src/requirements.txt (line 23))
Error: error building at STEP "RUN assemble": error while running runtime: exit status 1

An error occured (rc=1), see output line(s) above for details.
```

The `execution-environment.yml` is:

```yaml
---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-22/ee-supported-rhel8'
  EE_BUILDER_IMAGE: 'registry.redhat.io/ansible-automation-platform-22/ansible-builder-rhel8'

dependencies:
  python: requirements_ee.txt
  galaxy: collections/requirements.yml
  # system: bindep.txt

additional_build_steps:
  prepend: |
     RUN pip3 install --upgrade pip setuptools
  append:
     - RUN ls -salt /etc
```

The `collections/requirements.yml` file is:

```yaml
---
collections:
  - name: community.general
    source: https://galaxy.ansible.com

  - name: cisco.dnac
    source: https://galaxy.ansible.com

  - name: servicenow.itsm
    version: 2.0.0
    source: https://galaxy.ansible.com

  - name: paloaltonetworks.panos
    version: 3.0.0
    source: https://galaxy.ansible.com

  - name: cisco.ise
    version: 2.5.9
    source: https://galaxy.ansible.com

  - name: cisco.ios
    version: 4.0.0
    source: https://galaxy.ansible.com
```
The `requirements_ee.txt` file is:

```text
ansible==6.6.0
ansible-core==2.13.6
attrs==22.1.0
bindep==2.11.0
black==22.8.0
certifi==2022.6.15.1
cffi==1.15.1
charset-normalizer==2.1.1
ciscoisesdk==2.0.8
click==8.1.3
commonmark==0.9.1
coverage==6.4.4
cryptography==38.0.3
distro==1.8.0
dnac-sidekick==0.1.3
docutils==0.19
fastjsonschema==2.16.2
future==0.18.2
idna==3.3
iniconfig==1.1.1
Jinja2==3.1.2
lockfile==0.12.2
MarkupSafe==2.1.1
mypy-extensions==0.4.3
packaging==21.3
Parsley==1.3
pathspec==0.10.1
pbr==5.11.0
pexpect==4.8.0
platformdirs==2.5.2
pluggy==1.0.0
ptyprocess==0.7.0
py==1.11.0
pycparser==2.21
Pygments==2.13.0
pyparsing==3.0.9
pytest==7.1.3
pytest-cov==3.0.0
python-daemon==2.3.2
python-dotenv==0.21.0
PyYAML==6.0
requests==2.28.1
requests-toolbelt==0.9.1
requirements-parser==0.5.0
resolvelib==0.8.1
rich==12.5.1
six==1.16.0
tomli==2.0.1
types-setuptools==65.6.0.1
typing-extensions==4.3.0
urllib3==1.26.12
xmltodict==0.12.0
```

My web searches have not produced anything of value to resolve the issue, any insight would be appreciated.

**Comment by Shrews** [comment]
That error comes from `pip` when attempting to install the requirements from the various sources (the user requirements and individual collection requirements). You have a conflict that pip cannot resolve:

`requests==2.22.0,==2.28.1`

This says that want pip to install exactly version 2.22.0 _and_ 2.28.1.  The 2.28.1 requirement seems to be in your user requirements. Not sure which collection is requiring 2.22.0, but that is not a problem builder will be able to fix for you and you'll need to resolve the conflict yourself (by either removing the requirement from your user requirements file, or choosing a different collection version with a different `requests` requirement).

**Comment by Shrews** [comment]
Oh, a debugging note for you, if you use the `-v 3` option to `ansible-builder`, you should see output which lists where the requirements come from during the introspection stage. You'll need to run builder in an non-cached environment before you'll see the output.

**Comment by Shrews** [comment]
See similar issue https://github.com/ansible/ansible-builder/issues/348

**Comment by joelwking** [comment]
If this helps anyone encountering a similar issue. I pare down the requirements and collections to a minimum, build and run the image, then manually install the collections and Python requirements.

The `requirements_ee.txt` contains simply:

```text
ansible==6.6.0
ansible-core==2.13.6
PyYAML==6.0
```

The `collections/requirements_ee.yml` contains:

```yaml
collections:
  - name: community.general
    source: https://galaxy.ansible.com
```

```shell
ansible-builder build -v 3 --tag foo/bar  -f execution-environment.yml
```

Run the resulting image.

```shell
docker run  -it <imageid> /bin/bash
```

Detach from a container and leave it running, Press Ctrl-P, followed by Ctrl-Q, then copy the complete collection and requirements.

```shell
docker cp requirements.txt <containerid>:/tmp/requirements.txt
docker cp collections/requirements.yml <containerid>:/tmp/collections_requirements.yml
docker attach <containerid>
```

Install the Ansible collections and Python packages:

```shell
ansible-galaxy collection install -p /usr/share/ansible/collections/ -r /tmp/collections_requirements.yml
pip install -r /tmp/requirements.txt
```

After detaching from the container, create a new image `docker commit <containerid>`, then tag, login and push the image to **automationhub**.
