### ISSUE TITLE
EPEL_PACKAGES script not working on centos stream

### ISSUE THREAD

**Issue by gstorme** [ansible/ansible-builder#496]
Hi,

I tried building an image using ansible-builder 3.0.0rc1.
[This code](https://github.com/ansible/ansible-builder/blob/3.0.0rc1/ansible_builder/_target_scripts/install-from-bindep#L58) is not working when using the centos:stream9 image, with requirements that need packages from the EPEL repository.

```shell
$PKGMGR install -y $PKGMGR_OPTS --enablerepo epel $EPEL_PACKAGES
```

Build output:
```
#24 17.12 + '[' -f /output/bindep/epel.txt ']'
#24 17.12 ++ cat /output/bindep/epel.txt
#24 17.12 + EPEL_PACKAGES=python3-pyOpenSSL
#24 17.12 + '[' '!' -z python3-pyOpenSSL ']'
#24 17.12 + /usr/bin/dnf install -y --enablerepo epel python3-pyOpenSSL
#24 17.27 Error: Unknown repo: 'epel'
#24 ERROR: process "/bin/sh -c /output/scripts/install-from-bindep && rm -rf /output/wheels" did not complete successfully: exit code: 1
```

When replacing that line with these, it works fine.

```shell
	$PKGMGR install -y epel-release epel-next-release
        $PKGMGR install -y $PKGMGR_OPTS $EPEL_PACKAGES
```

Build output:
```
#24 16.76 + '[' -f /output/bindep/epel.txt ']'
#24 16.76 ++ cat /output/bindep/epel.txt
#24 16.76 + EPEL_PACKAGES=python3-pyOpenSSL
#24 16.76 + '[' '!' -z python3-pyOpenSSL ']'
#24 16.76 + /usr/bin/dnf install -y epel-release epel-next-release
#24 17.05 Last metadata expiration check: 0:00:07 ago on Wed Apr 26 23:55:21 2023.
#24 17.13 Dependencies resolved.
#24 17.13 ================================================================================
#24 17.13  Package                 Architecture Version         Repository           Size
#24 17.13 ================================================================================
#24 17.13 Installing:
#24 17.13  epel-next-release       noarch       9-2.el9         extras-common       8.1 k
#24 17.13  epel-release            noarch       9-2.el9         extras-common        17 k
#24 17.13 
#24 17.13 Transaction Summary
#24 17.13 ================================================================================
#24 17.13 Install  2 Packages
#24 17.13 
#24 17.13 Total download size: 25 k
#24 17.13 Installed size: 26 k
#24 17.13 Downloading Packages:
#24 17.55 (1/2): epel-next-release-9-2.el9.noarch.rpm     225 kB/s | 8.1 kB     00:00    
#24 17.56 (2/2): epel-release-9-2.el9.noarch.rpm          335 kB/s |  17 kB     00:00    
#24 17.56 --------------------------------------------------------------------------------
#24 17.56 Total                                            57 kB/s |  25 kB     00:00     
#24 17.58 CentOS Stream 9 - Extras packages               2.1 MB/s | 2.1 kB     00:00    
#24 17.63 Importing GPG key 0x1D997668:
#24 17.63  Userid     : "CentOS Extras SIG (https://wiki.centos.org/SpecialInterestGroup) <security@centos.org>"
#24 17.63  Fingerprint: 363F C097 2F64 B699 AED3 968E 1FF6 A217 1D99 7668
#24 17.63  From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-Extras-SHA512
#24 17.64 Key imported successfully
#24 17.66 Running transaction check
#24 17.66 Transaction check succeeded.
#24 17.66 Running transaction test
#24 17.67 Transaction test succeeded.
#24 17.67 Running transaction
#24 17.69   Preparing        :                                                        1/1 
#24 17.69   Installing       : epel-release-9-2.el9.noarch                            1/2 
#24 17.70   Installing       : epel-next-release-9-2.el9.noarch                       2/2 
#24 17.71   Running scriptlet: epel-next-release-9-2.el9.noarch                       2/2 
#24 17.76   Verifying        : epel-next-release-9-2.el9.noarch                       1/2 
#24 17.76   Verifying        : epel-release-9-2.el9.noarch                            2/2 
#24 17.79 
#24 17.79 Installed:
#24 17.79   epel-next-release-9-2.el9.noarch          epel-release-9-2.el9.noarch         
#24 17.79 
#24 17.79 Complete!
#24 17.83 + /usr/bin/dnf install -y python3-pyOpenSSL
#24 18.81 Extra Packages for Enterprise Linux 9 - x86_64   22 MB/s |  15 MB     00:00    
#24 25.32 Extra Packages for Enterprise Linux 9 - Next -  719 kB/s | 1.6 MB     00:02    
#24 26.32 Last metadata expiration check: 0:00:02 ago on Wed Apr 26 23:55:36 2023.
#24 27.37 Dependencies resolved.
#24 27.38 ================================================================================
#24 27.38  Package                  Architecture  Version               Repository   Size
#24 27.38 ================================================================================
#24 27.38 Installing:
#24 27.38  python3-pyOpenSSL        noarch        21.0.0-1.el9          epel         90 k
#24 27.38 
#24 27.38 Transaction Summary
#24 27.38 ================================================================================
#24 27.38 Install  1 Package
#24 27.38 
#24 27.38 Total download size: 90 k
#24 27.38 Installed size: 389 k
#24 27.38 Downloading Packages:
#24 28.13 python3-pyOpenSSL-21.0.0-1.el9.noarch.rpm       290 kB/s |  90 kB     00:00    
#24 28.13 --------------------------------------------------------------------------------
#24 28.13 Total                                           120 kB/s |  90 kB     00:00     
#24 28.14 Extra Packages for Enterprise Linux 9 - x86_64  1.6 MB/s | 1.6 kB     00:00    
#24 28.21 Importing GPG key 0x3228467C:
#24 28.21  Userid     : "Fedora (epel9) <epel@fedoraproject.org>"
#24 28.21  Fingerprint: FF8A D134 4597 106E CE81 3B91 8A38 72BF 3228 467C
#24 28.21  From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9
#24 28.21 Key imported successfully
#24 28.23 Running transaction check
#24 28.23 Transaction check succeeded.
#24 28.23 Running transaction test
#24 28.24 Transaction test succeeded.
#24 28.24 Running transaction
#24 28.25   Preparing        :                                                        1/1 
#24 28.27   Installing       : python3-pyOpenSSL-21.0.0-1.el9.noarch                  1/1 
#24 28.28   Running scriptlet: python3-pyOpenSSL-21.0.0-1.el9.noarch                  1/1 
#24 28.65   Verifying        : python3-pyOpenSSL-21.0.0-1.el9.noarch                  1/1 
#24 28.68 
#24 28.68 Installed:
#24 28.68   python3-pyOpenSSL-21.0.0-1.el9.noarch                                         
```

**Comment by Akasurde** [comment]
@gstorme Thanks for reporting this issue. Could you please provide the EE file used to build this image? Thanks.

**Comment by gstorme** [comment]
EE file:

```yaml
---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream9

dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.0rc1
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt

additional_build_files:
    - src: files/ansible.cfg
      dest: configs
    - src: files/default_ansible.tmpl
      dest: files

additional_build_steps:
  prepend_galaxy:
    - ADD _build/configs/ansible.cfg ~/.ansible.cfg

  append_final:
    - COPY _build/files/default_ansible.tmpl /etc/default/default_ansible.tmpl
    - RUN envsubst < /etc/default/default_ansible.tmpl > /etc/default/ansible
    - RUN rm -f /etc/default/default_ansible.tmpl
```

galaxy:

```yaml
---
collections:
  - name: awx.awx
  - name: community.general
  - name: ansible.windows
  - name: ansible.posix
  - name: ansible.netcommon
  - name: community.windows
    version: '1.10.0'
  - name: community.mysql
  - name: community.docker
  - name: community.crypto
  - name: community.postgresql
  - name: community.rabbitmq
  - name: community.mongodb
  - name: chocolatey.chocolatey
```

python:

```
python3-memcached
psutil
pyjwt
requests
passgen
passlib
netaddr
pywinrm[credssp]
jmespath
Jinja2==3.1.2
dnspython
netapp-ontap
netapp-lib
kubernetes
python-dateutil
envsubst
```

**Comment by sivel** [comment]
This is expected behavior. Although we have support code to install deps from epel, as evidenced by the line you point to in `install-from-bindep` we purposefully do not automatically install the repo.  This is done as a safety net, for users that may not want arbitrary repositories enabled without explicit knowledge for satisfying deps.

As such, you will need to add `epel-release [platform:rpm]` as a system dependency so that it is available.

**Comment by CayoM** [comment]
fortunately I came across this issue after trying to install packages via bindep.txt and failing bad. Im really curious to know if what I was trying is possible using the official base/builder images.

I wanted to install wireguard-tools via bindep.txt but the package was not found. Trying to add epel-release was also not possible (apparently because the repository was not enabled - codeready-builder-for-rhel-9-$(arch)-rpms). So, not sure how to even add repositories, since the Images don't have subscription-manager, dnf and yum binaries. manually trying to add via microdnf didn't work aswell.

The only way I managed to get things working was 
```
bindep.txt
epel-release [platform:rpm]
wireguard-tools [platform:rpm]

execution-environment.yml
---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream9

dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.0rc1
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
```

However, I wonder what I would have to do in order to get it to work in this setup:
```
bindep.txt
wireguard-tools [platform:rpm]

execution-environment.yml
---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: registry.redhat.io/ansible-automation-platform-22/ee-minimal-rhel8:latest
  EE_BUILDER_IMAGE: registry.redhat.io/ansible-automation-platform-22/ansible-builder-rhel8:latest

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
```

Probably if I would like to go the official way, I would have to activate some subscription, then activate the repository "rhel-9-for-x86_64-appstream-rpms" or "rhel-9-for-x86_64-appstream-eus-rpms" (as described here https://access.redhat.com/downloads/content/wireguard-tools/1.0.20210914-2.el9/x86_64/fd431d51/package) to install the needed package, but again, without subscription-manager im not sure how to handle this... TBH I kinda dislike this way, because I would have to pass credentials via build_args and manage it differently.

Any hints? TIA
