### ISSUE TITLE
ansible builder fails when using dict for galaxy requirements.

### ISSUE THREAD

**Issue by sean-m-sullivan** [ansible/ansible-builder#568]
When using the following definition in a execution_requirements file
```
dependencies:
  galaxy:
  - name: awx.awx
    version: 21.9.0
  - infra.controller_configuration
  - infra.ah_configuration
  ```
  
  Builder will fail with
  ```
  jsonschema.exceptions.ValidationError: {'name': 'awx.awx', 'version': '21.9.0'} is not of type 'string'

Failed validating 'type' in schema[2]['items']:
    {'type': 'string'}

On instance[0]:
    {'name': 'awx.awx', 'version': '21.9.0'}

During handling of the above exception, another exception occurred:

ansible_builder.exceptions.DefinitionError: {'name': 'awx.awx', 'version': '21.9.0'} is not of type 'string'
```
I tried to fix this on my own, but was unable to, I believe its in here, and should allow a list of dicts.
file: https://github.com/sean-m-sullivan/ansible-builder/blob/5efe17fbb5c71e1b6dde354350963d598e3d57a6/src/ansible_builder/ee_schema.py#L228

Also this is based on the following galaxy documentation:
https://docs.ansible.com/ansible/devel/collections_guide/collections_installing.html#install-multiple-collections-with-a-requirements-file
specifically
You can specify the following keys for each collection entry:
        name
        version
        signatures
        source
        type

**Comment by kurokobo** [comment]
I think the list should be under `collections` (or `roles`):

```yaml
dependencies:
  galaxy:
    collections:   👈👈👈
      - name: awx.awx
        version: 21.9.0
      - infra.controller_configuration
      - infra.ah_configuration
```
