### ISSUE TITLE
Python interpreter cannot find site packages

### ISSUE THREAD

**Issue by shatakshiiii** [ansible/ansible-builder#589]
**SUMMARY**

Building an execution-environment with builder v3 cannot find a path to python interpreter. And hence not able to find the python packages that are installed inside that path.

**STEPS TO REPRODUCE**

1. Create a EE image localhost/ee:0.0.1 with file `execution-environment.yml` with given content. 

```
---
version: 3

images:
  base_image:
    name: quay.io/fedora/python-311:latest

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
      - community.general
  python:
    - ansible-lint
 ```
 2. Build the EE with ansible-builder 3.0.0:
 ```
ansible-builder build -t ee:0.0.1
```
3. Run: `podman run -it ee:0.0.1` and after that do: `python -m site`

**Expected behaviour**

I should see a path to: `/usr/local/lib/python3.11/site-packages` in the list of sys.path

**Actual Behaviour**

There is no path mentioned as: /usr/local/lib/python3.11/site-packages inside that EE.
```
(app-root) python -m site
sys.path = [
    '/home/user/Ansible/ansible-navigator',
    '/usr/lib64/python311.zip',
    '/usr/lib64/python3.11',
    '/usr/lib64/python3.11/lib-dynload',
    '/opt/app-root/lib64/python3.11/site-packages',
    '/opt/app-root/lib/python3.11/site-packages',
]
USER_BASE: '/root/.local' (doesn't exist)
USER_SITE: '/root/.local/lib/python3.11/site-packages' (doesn't exist)
ENABLE_USER_SITE: False
```
Moreover: `pip freeze` inside that EE gives no output as it can't find any installed python package.
```
(app-root) pip freeze
(app-root) 
```
