### ISSUE TITLE
Offline building with v3.0

### ISSUE THREAD

**Issue by nodje** [ansible/ansible-builder#606]
I'm not able to update my configuration to build with v3.0 since I'm offline.

There was an option to use a local `ubi.repo` file that apparently disappeared in v3.0. Or at least I can't find it.

I use 
```
options:
  package_manager_path: /usr/bin/microdnf
```
since I use Red Hat images, but the build is stuck looking for some public repo that is not accessible for me:
```
Downloading metadata...
error: cannot update repo 'ubi-9-baseos-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Curl error (6): Couldn't resolve host name for https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi9/9/x86_64/baseos/os/repodata/repomd.xml [Could not resolve host: cdn-ubi.redhat.com]
```

How can I provide a local repo option that would lead to something 1.0 equivalent in Containfile:
```
# this section added
ADD ubi.repo /etc/yum.repos.d/ubi.repo
ADD pip.conf /etc/pip.conf
# end additions
```

**Comment by Akasurde** [comment]
Please take a look at https://ansible.readthedocs.io/projects/builder/en/latest/scenario_guides/scenario_copy/#copying-arbitratory-files-to-ee for copying arbitrary files.

tl;dr - 

```
additional_build_files:
  # copy arbitrary files next to this EE def into the build context - we can refer to them later...
  - src: files/ubi.repo
    dest: configs
  - src: files/pip.conf
    dest: configs

additional_build_steps:
  prepend_base:
    - COPY _build/configs/ubi.repo /etc/yum.repos.d/ubi.repo
    - COPY _build/configs/pip.conf /etc/pip.conf
```
