### ISSUE TITLE
python_interpreter is not being used by ansible

### ISSUE THREAD

**Issue by nodje** [ansible/ansible-builder#608]
AFAIU, using the settings
```
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
```
is getting installed and used by all python commands during build time.

But it doesn't get set as the default interpreter on the build image AFAIK.

I'm using ansible-builder==3.0.0 of course and base image I use is `ansible-automation-platform-24/ee-minimal-rhel9:latest`

Is not python_interpreter also meant as being the base interpreter for ansible's commands?

**Comment by kurokobo** [comment]
F.Y,I., I don't know if this is the correct answer for you, but some python files that passed to the image by AWX/AAP contains hard-coded shebang, `#! /usr/bin/env python3`: https://github.com/ansible/awx/blob/159dd62d84df3ac14d274571724eee0324c2ca61/awx/main/tasks/jobs.py#L319

So if there is no `python3` on your image, the image can't be used with AWX/AAP.

To avoid this, I have a workaround: 

```yaml
additional_build_steps:
  append_base:
    - RUN alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 0
```

This makes your `python3.11` globally available as `python3` on your image.

**Comment by nodje** [comment]
Thanks, seems to work with `ansible-automation-platform-24/ee-minimal-rhel9:latest` when using ansible-builder v3 build command.
I had previously tested this manually from within a container from that same image but built with an ansible-builder-v1's generated ContainFile and the  alternatives` cmd was n't available for some reason.

BUT, it produces a side-effect:
```
[4/4] STEP 12/26: RUN /output/scripts/check_ansible $PYCMD
+ PYCMD=/usr/bin/python3.11
+ '[' -z /usr/bin/python3.11 ']'
+ '[' '!' -x /usr/bin/python3.11 ']'
+ ansible --version
Traceback (most recent call last):
  File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ansible", line 33, in <module>
    sys.exit(load_entry_point('ansible-core==2.15.4', 'console_scripts', 'ansible')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/ansible", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for ansible-core
+ '[' 1 -ne 0 ']'
+ cat
**********************************************************************
ERROR - Missing Ansible installation

  An Ansible installation cannot be found in the final builder image.

  Ansible must be installed in the final image. If you are using a
  recent enough version of the execution environment file, you may
  use the 'dependencies.ansible_core' configuration option to install
  Ansible for you, or use 'additional_build_steps' to manually do
  this yourself. Alternatively, use a base image with Ansible already
  installed.
**********************************************************************
+ exit 1
``` 

ContainerFile:
```
RUN $PKGMGR install $PYPKG -y ; if [ -z $PKGMGR_PRESERVE_CACHE ]; then $PKGMGR clean all; fi
RUN $PYCMD -m ensurepip
RUN $PYCMD -m pip install --no-cache-dir $ANSIBLE_INSTALL_REFS
COPY _build/scripts/ /output/scripts/
COPY _build/scripts/entrypoint /opt/builder/bin/entrypoint
RUN alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 0
```
I suspect that because pip install is run before the alternatives directive, it kinds of mess up the dependencies installed with 3.9.
Not too sure what's happening here, it feels that these deps should be available,.
Running ` $PYCMD -m pip install --no-cache-dir $ANSIBLE_INSTALL_REFS`after alternatives again doesn't seem to help.

So anyways, not a workable solution, which means python_interpreter cannot be used for ansible today.
But still wondering why? should it not be the default behaviour when you choose to set `python_interpreter`

**Comment by kurokobo** [comment]
Hmm, I can't reproduce the error.
Could you provide your whole files (`execution-environment.yml` etc.) and how do you test it?

My examples:

```yaml
---
version: 3
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest
options:
  package_manager_path: /usr/bin/microdnf
dependencies:
  python_interpreter:
    package_system: python3.11
    python_path: /usr/bin/python3.11
  ansible_core:
    package_pip: ansible-core~=2.15
  ansible_runner:
    package_pip: ansible-runner~=2.3
  system: dependencies/bindep.txt
  python: dependencies/requirements.txt
  galaxy: dependencies/requirements.yml
additional_build_files:
  - src: files/ansible.cfg
    dest: configs
additional_build_steps:
  append_base:
    - RUN alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 0
  prepend_galaxy:
    - ADD _build/configs/ansible.cfg ~/.ansible.cfg
```

This can be built without any errors and can be confirmed that ansible uses Python 3.11.

```bash
# Build
$ ansible-builder build --tag registry.example.com/ansible/ee:2.15-custom --container-runtime docker --verbosity 3

# Test
$ docker run --rm -it registry.example.com/ansible/ee:2.15-custom bash
bash-5.1$ ansible --version
ansible [core 2.15.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.11/site-packages/ansible
  ansible collection location = /runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.2 (main, May 24 2023, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True

bash-5.1$ python3 -V
Python 3.11.2
```

**Comment by nodje** [comment]
Nice, it gives me some hope:

Execution-environment.yml
```
---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre -c'

dependencies:
  #  ansible_core:
  #    package_pip: ansible-core==2.15.4
  ansible_runner:
    package_pip: ansible-runner==2.3.4
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"

images:
  base_image:
    name: s01vl9989234.fr.net.intra/ansible-automation-platform-24/ee-minimal-rhel9:latest

# Custom package manager path for the RHEL based images
options:
  package_manager_path: /usr/bin/microdnf

additional_build_files:
  - src: ansible.cfg
    dest: configs
  - src: ubi9.repo
    dest: configs
  - src: pip.conf
    dest: configs
  - src: rootCA.crt
    dest: configs

additional_build_steps:
  prepend_base:
    - RUN rm -rf /etc/yum.repos.d/*
    - COPY _build/configs/ubi9.repo /etc/yum.repos.d/ubi9.repo
    - COPY _build/configs/pip.conf /etc/pip.conf
    - COPY _build/configs/rootCA.crt /etc/pki/ca-trust/source/anchors/rootCA.crt
    - RUN update-ca-trust
  prepend_galaxy:
    - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg
    - ENV ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_URL=https://s01vl9989234.fr.net.intra
  append_base:
    - RUN alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 0

  prepend_final: |
    RUN whoami
    RUN cat /etc/os-release
  append_final:
    - RUN echo This is a post-install command!
```
NB: ansible-core is installed from requirements.txt
I don't see any other major difference.

If it works without it using python3.9 it should also with python3.11.
Unless there's an ansible version included in the base image... which might well be the case on AAP2 EE images!
