### ISSUE TITLE
Error when building an EE without requirements.yml

### ISSUE THREAD

**Issue by NotAFile** [ansible/ansible-builder#641]
The behaviour of #290 appears to have returned again:

execution-image.yml
```
---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream9

dependencies:
    ansible_core:
        package_pip: ansible-core==2.15.0
    ansible_runner:
        package_pip: ansible-runner==2.3.2
    galaxy: requirements.yml

additional_build_files:
    - src: files/ansible.cfg
      dest: configs

additional_build_steps:
    prepend_final:
        - COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg

options:
    package_manager_path: /usr/bin/microdnf
```

requirements.yml
```
---
collections: []
```
Error:
```
Error: building at STEP "COPY _build/configs/ansible.cfg /etc/ansible/ansible.cfg": checking on sources under [...] copier: stat: "/_build/configs/ansible.cfg": no such file or directory
```
