### ISSUE TITLE
ansible-builder version 3 has broken compatibility with schema version 1

### ISSUE THREAD

**Issue by Shrews** [ansible/ansible-builder#646]
The builder image is not being used in a v1 EE definition (neither the default value nor the explicitly defined value).

Example A:

```
---
version: 1
```

Example B:

```
---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:latest'
  EE_BUILDER_IMAGE: 'quay.io/ansible/ansible-builder:latest'
```

Both examples produce a `Containerfile` that will always use the base image for the builder image. E.g.,

```
...
# Builder build stage
FROM base as builder
...
```

It does not appear that we have any tests to cover this situation.
