### ISSUE TITLE
Ansible builder fails after upgrade to 3.1.0

### ISSUE THREAD

**Issue by jorgenspange** [ansible/ansible-builder#688]
Ansible-builder fails after upgrade to 3.1.0 from 3.0.1 due to:

```yaml
ERROR: Double requirement given: netaddr>=0.10.1 (from -r /tmp/src/requirements.txt (line 13)) (already in netaddr (from -r /tmp/src/requirements.txt (line 4)), name='netaddr')
```

In my requirements file this is the only thing specified:

ansible-pylibssh>=1.1.0

Tried specifying newer version of netaddr aswell, with no dice.

Once I downgrade to ansible-builder to 3.0.1 everything works.

**Comment by sean-m-sullivan** [comment]
Running into same issue with netaddr from multiple repos, even if I specify a newer version of netaddr. most Cisco/netcommon collections started this requirement this last week setting more than .10

**Comment by Shrews** [comment]
Not enough info here for me to reproduce this error. Please provide an example EE definition file, and any associated extras, like collections being used, that reproduces this error.

**Comment by sean-m-sullivan** [comment]
---
version: 3

dependencies:
  galaxy:
    collections:
      - name: ansible.utils
        version: 5.0.0
      - ansible.network
      - name: ansible.netcommon
        version: 7.0.0
      - name: cisco.ios
        version: 9.0.0
      - name: cisco.iosxr
        version: 10.0.0
      - name: cisco.nxos
        version: 9.0.0
      - name: cisco.asa
        version: 6.0.0
      - name: ansible.posix
      - name: community.general
  python:
    - dnspython
    - netaddr
    - scp # Used for netcommon.net_put
  system:
    - jq
    # - curl Needed but built into UBI:9


images:
  base_image:
    name: >-
      registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

**Comment by sean-m-sullivan** [comment]
```yaml

---
version: 3

dependencies:
  galaxy:
    collections:
      - name: ansible.utils
        version: 5.0.0
      - ansible.network
      - name: ansible.netcommon
        version: 7.0.0
      - name: cisco.ios
        version: 9.0.0
      - name: cisco.iosxr
        version: 10.0.0
      - name: cisco.nxos
        version: 9.0.0
      - name: cisco.asa
        version: 6.0.0
      - name: ansible.posix
      - name: community.general
  python:
    - dnspython
    - netaddr
    - scp # Used for netcommon.net_put
  system:
    - jq
    # - curl Needed but built into UBI:9


images:
  base_image:
    name: >-
      registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest
```

**Comment by jorgenspange** [comment]
Here is my ee definition file aswell:

```yaml
---
version: 3

dependencies:
  galaxy:
    collections:
      - name: ansible.posix
      - name: ansible.utils
      - name: ansible.netcommon
      - name: community.general
      - name: cisco.ios
      - name: cisco.iosxr
      - name: cisco.ise
      - name: cisco.nxos
  python:
    - ansible-pylibssh>=1.1.0
    - ciscoisesdk

images:
  base_image:
    name: >-
      registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest
```
