### ISSUE TITLE
[Solved] Build fails in some kind of permission issue

### ISSUE THREAD

**Issue by ladd-a** [ansible/ansible-builder#711]
I've had to recreate my build environment and for some reason there is a permission issue at pip_install step:
```
[1/4] STEP 15/16: RUN /output/scripts/pip_install $PYCMD
/bin/sh: line 1: /output/scripts/pip_install: Permission denied
Error: error building at STEP "RUN /output/scripts/pip_install $PYCMD": error while running runtime: exit status 126
```

At first I suspected this is an issue with one of the new packages I added to the build dependencies, but removing that had no effect. Also ruled out system as it seems to happen despite disabling apparmor and trying build as root on ubuntu 22.04.

This image build fine approx. 10 months ago in similar environment (using same ubuntu version).

This is my execution-environment.yml:
```yaml
---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--pre'

dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  python:
    - jmespath
    - pyVim
    - pyVmomi
    - pexpect
    - lxml
    - pymssql
    - cryptography
    - git+https://github.com/vmware/vsphere-automation-sdk-python.git
  galaxy: galaxy.yaml

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest

options:
  package_manager_path: /usr/bin/microdnf
```

```bash
$ adt --version
ansible-builder                          3.1.0
ansible-core                             2.17.4
ansible-creator                          24.9.0
ansible-dev-environment                  24.9.0
ansible-dev-tools                        24.8.0
ansible-lint                             24.9.0
ansible-navigator                        24.9.0
ansible-sign                             0.1.1
molecule                                 24.8.0
pytest-ansible                           24.9.0
tox-ansible                              24.9.0

$ python3 --version
Python 3.10.12

$ podman --version
podman version 3.4.4
```

Also the builder seems to run earlier python version by default, is that a problem?:
```
[1/4] STEP 13/16: RUN $PYCMD -V
Python 3.9.18
```
