### ISSUE TITLE
Inline requirements result in context files that are readable only by owner

### ISSUE THREAD

**Issue by jeffcpullen** [ansible/ansible-builder#747]
### Ansible Builder version

3.1.0

### Python version

Python 3.13.2 (main, Feb  4 2025, 14:51:09) [Clang 16.0.0 (clang-1600.0.26.6)]

### Operating System and Environment

```console
Same results seen on macOS Sequoia 15.5 and within `ghcr.io/ansible/community-ansible-dev-tools:v25.5.1`
```

### Container Runtime

podman version 5.3.1

### Summary

We have a Gitlab pipeline that runs `ansible-builder create` to create and store the EE artifacts prior to the build and publish of the new EE. This has been working for a while, but stopped working when we added the system dependencies option to the EE definition file.

Adding system dependencies creates an additional bindep.txt file that we didn't previously have. As the pipeline attempts to upload all the files created by ansible-builder, we get a permission error on `context/_build/bindep.txt`. We discovered that the bindep.txt file get different, and more restrictive permissions applied to it than the rest of the build artifacts.

```
(.venv) jpullen@macos ee-2.5 % ansible-builder create --file execution-environment.yml 
Complete! The build context can be found at: /Users/jpullen/git/example_ees/ee-2.5/context
(.venv) jpullen@macos ee-2.5 % ls -al context 
total 8
drwxr-xr-x@ 6 jpullen  staff   192 Jun 11 10:13 _build
drwxr-xr-x@ 4 jpullen  staff   128 Jun 11 10:13 .
drwxr-xr-x@ 7 jpullen  staff   224 Jun 11 10:13 ..
-rw-r--r--@ 1 jpullen  staff  3890 Jun 11 10:13 Containerfile
(.venv) jpullen@macos ee-2.5 % ls -al context/_build 
total 24
drwxr-xr-x@ 6 jpullen  staff  192 Jun 11 10:13 .
drwxr-xr-x@ 4 jpullen  staff  128 Jun 11 10:13 ..
-rw-------@ 1 jpullen  staff   34 Jun 11 10:13 bindep.txt
-rw-r--r--@ 1 jpullen  staff   80 Jun 11 09:49 requirements.txt
-rw-r--r--@ 1 jpullen  staff  663 Jun 11 09:49 requirements.yml
drwxr-xr-x@ 9 jpullen  staff  288 Jun 11 10:13 scripts
```

I can't think of a reason this file would be more sensitive and require greater restrictions, so I'm assuming this is a bug. 

### Steps to reproduce

1. pip install ansible-builder
2. Create an EE file with system dependencies similar to this

execution-environment.yml
```yaml
---
version: 3
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest
options:
  package_manager_path: /usr/bin/microdnf
dependencies:
  system:
    - gcc
    - systemd-devel
    - python3.11-devel
  python_interpreter:
    package_system: python3.11
    python_path: /usr/bin/python3.11
  ansible_core:
    package_pip: ansible-core>=2.16
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
...
```

3. Run `ansible-builder create --file execution-environment.yml`
4. Observe the different permissions for the created file `ls -al context/_build`

### Expected Results

bindep.txt should leverage the same set of file permissions as the rest of the build artifacts (644).

### Actual Results

The bindep.txt has unique permissions that do not include group and other read permissions.

**Comment by Shrews** [comment]
This happens if you declare your system (or Python) requirements inline within the EE file. If you place your requirements in external files, you should see different behavior.

Inline requirements are first written to a file in the temporary directory of your system before builder copies the file into the `context/_build` directory. Temp files are created with more restrictive permissions.

**Comment by Shrews** [comment]
I think this could easily be improved, but the workaround above should get you past it for now.

**Comment by jeffcpullen** [comment]
@Shrews thank you for the quick reply, workaround and related PR. I switched to using the format you suggested (shown below) and did not have the permissions issues seen with the inline requirements.

```yaml
---
version: 3
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest
options:
  package_manager_path: /usr/bin/microdnf
dependencies:
  system: bindep.txt
  python_interpreter:
    package_system: python3.11
    python_path: /usr/bin/python3.11
  ansible_core:
    package_pip: ansible-core>=2.16
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
...
```
